services:

  db:
    container_name: plants-api-db
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - plants-api-db-volume:/var/lib/postgresql

  backend:
    container_name: plants-api-backend
    build: .
    image: nnimens/plants-api:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  plants-api-db-volume: